# Generated by Django 3.0.7 on 2020-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200817_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
