# Generated by Django 3.0.7 on 2020-08-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200817_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
