# Generated by Django 3.0.7 on 2020-11-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_messeges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messeges',
        ),
    ]
