# Generated by Django 3.0.7 on 2020-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_messeges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messeges',
        ),
    ]
