# Generated by Django 3.0.7 on 2020-11-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201104_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Report',
        ),
    ]
