# Generated by Django 3.0.7 on 2020-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201104_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_complaint', models.DateField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('street_address1', models.CharField(max_length=3000)),
                ('street_address2', models.CharField(max_length=3000)),
                ('city', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('postalcode', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=300)),
                ('date_incident', models.DateField()),
                ('incident_location', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
