# Generated by Django 3.0.7 on 2020-11-04 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201104_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecomplaints',
            name='date_complaint',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
