# Generated by Django 3.0.7 on 2020-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201104_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RescueComplaints',
            new_name='RescueComplaint',
        ),
    ]
