# Generated by Django 3.0.7 on 2020-11-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_feedback_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback_Notes',
            new_name='Feedback_Note',
        ),
    ]
